### ISSUE TITLE
Trying to generate entities from metadata gives modelLibrary interface error

### ISSUE THREAD

**Issue by apawsey** [Breeze/breeze.tooling#2]
I can generate the CSDL metadata easily enough (had to add my connection string to the metadatagenerator.exe.config file), but when I try and use the tsgen script I get the following error:

`Unexpected error occurred: Unable to locate the default implementation of the 'modelLibrary' interface.  Possible options are 'ko', 'backingStore' or 'backbone'. See the breeze.config.initializeAdapterInstances method.`

**Comment by marcelgood** [comment]
This issue is caused by a recent change to Breeze. I will fix it shortly and post an update.

**Comment by steveschmitt** [comment]
We forgot to update tsgen.js for the latest version of breeze-client, which uses breeze.base.debug.js as the default js file instead of breeze.debug.js. The breeze.debug.js file has a default modelLibrary, but breeze.base.debug.js does not.

I've updated tsgen.js to use breeze.debug.js. Please get the latest and try again.

**Comment by marcelgood** [comment]
Looks like @steveschmitt missed two more places where the fixed need to be made. Just checked those in as well.
