### ISSUE TITLE
// This is might be because we have a DbFirst DbContext, so let's try it out.

### ISSUE THREAD

**Issue by mikemichaelis** [Breeze/breeze.tooling#7]
From MetadataGenerator/Program.cs:

/// When using a DbFirst approach EF thwros two kind of exceptions:
**/// 1. InvalidOperationException is there is no connection string for the DbContext we are working on.**
/// 2. UnintentionalCodeFirstException if it finds the connection string for the DbContext. 
///     UnintentionalCodeFirstException inherits from InvalidOperationException

The only way I can get a DbFirst EF 6.0 model to produce Metadata is to uncomment:

            catch (InvalidOperationException iex) // This is might be because we have a DbFirst DbContext, so let's try it out.
            {
                try
                {
                    return EFContextProvider<object>.GetMetadataFromDbFirstAssembly(type.Assembly, Options.ResourcePrefix);
                }
                catch (Exception ex)
                {
                    Console.WriteLine("An exception was thrown while processing the dbfirst assembly {0}. {1}", type.Assembly.FullName, ex);
                }
            }

The InvalidOperationException thrown does have the message:

"No connection string named 'TIPS_Corn_DevEntities' could be found in the application config file."

as is indicated in the /// 1 comment above, however the connection string does exist and is properly named within the specified .dll.config.  Properly catching and executing 

GetMetadataFromDbFirstAssembly()

will properly generate the metadata.

Why is this code commented out?

Thanks,
Mike

**Comment by mikemichaelis** [comment]
Locally I have modified MetadataGenerator to accept a command line argument to allow for metadata generation of EF 6 DbFirst DbContext.

I would also suggest better handling when MetadataGenerator is used with an EF 5 DbContext as currently nothing is written and nothing is logged to the console.  Maybe it is documented somewhere that MetadataGenerator only works with EF 6?  The reason EF 5 does not work is there is a failure loading the EF 5 libs in t.IsSubclassOf(typeof(DbContext)) of GetDbContextTypesFromAssembly()

Please at least better document MetadataGenerator as after reading a lot about BreezeJS and getting quite excited, I hit a brick wall with the very first step in the process, generating metadata from my existing EF models (EF 5 & DbFirst).  Not a very good first start.  I'm glad I worked through this, as I'm still excited to use BreezeJS, but I must admit my initial frustration.

<< mike

**Comment by mikemichaelis** [comment]
One more thing, your existing docs for MetadataGenerator are wrong.  The docs show the parameters with the full parameter name but only a single leading dash.  Ie

-native

should be

--native OR -n

Regardless neither of those actually work, even in temphire.angular - edit package.json/metadata:

"metadata": ".\\tools\\bin\\MetadataGenerator.exe -i ..\\..\\BreezeTest\\test-model\\notModel\\bin\\Debug\\notModel.dll -o metadata.json -n"

Produces nothing as does --native.  There is a race condition between when you launch the Node Process to convert the json and you delete the source json itself.  IE

ConvertCsdlToNative(tempFileName, fileNameFullPath);
File.Delete(tempFileName);

Opps................seriously wish I hadn't touted BreezeJS to my team. I'm probably going to end up looking like an idiot.......

<< mike

**Comment by marcelgood** [comment]
Sorry about your experience. The Breeze Tooling repo is a free tool that we put out there as a convenience to generate the TypeScript classes for Breeze entities as apposed to having to code them manually. It's intention is not to generate the metadata. It spits out the metadata in order to use it for the TypeScript class generation, but you don't need this tool to generate the metadata. Breeze can directly fetch the Metadata from an EF back-end. It definitely doesn't support EF5. EF5 is old and has been outdated for a while now. 

As with Breeze itself, this tool is open source and free to use. If it doesn't work for you or you find bugs, you are free to contribute any fixes. We use the tool quite successfully for own projects. Once in a while we run into an issue and fix it.

We contribute things like this the community as we think somebody might find it helpful, but this is not a commercial product nor are we charging money for it, so use it at your own risk. We do offer Breeze support and consulting if you prefer a more commercial relationship with us and need help with the tooling.

**Comment by mikemichaelis** [comment]
So, I'm moving to the next step, actually generate the entities, and I get this from temphire.angular:

PS X:\Git\temphire.angular\TempHire> npm run entities

> temphire-angular@1.0.0 entities X:\Git\temphire.angular\TempHire
> node ./tools/tsgen.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'breeze-client/breeze.debug'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (X:\Git\temphire.angular\TempHire\tools\tsgen-core.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

to reproduce this is easy, just clone the repository

git clone https://github.com/Breeze/temphire.angular.git

now lets delete the the entities folder (since like all NEW USERS, this folder will be empty)

rimraf .\app\core\entities

now generate metadata (obviously build the dll first from your Code First DbContext - meaning you don't need that commented code that started this whole issue) and then generate your entities:

npm run metadata
npm run entities

BOOM!

**Comment by mikemichaelis** [comment]
marcelgood,

Thanks for your completely useless response.  Would you at least try to address the issues, as this conversation is under the 'issues' sections of your repo.

I do at least better understanding this project now.  

The simple point is that the tooling does not work and is very poorly documented compared to BreezeJS itself.  The use of the tooling destroys the first impression of trying to use Breeze.

I disagree with you the purpose of MetadataGenerator is to generate the metadata.

Breeze can directly fetch the Metadata from an EF back-end - yes, I'm aware of this, however going that route does not leave you with nicely typed entities for use on the client side.

Very sloppy stuff.  Maybe BreezeJS is awesome, I'll be the judge of that myself, but otherwise this has been the worst experience I've had with a client side library.  Wow.

<< mike

**Comment by mikemichaelis** [comment]
If you love your code like I do, then just try to see it from my perspective.

I have an DbContext (EF5).  Try to generate typescript classes.  Fail.  Recreate DbContext in EF6.  Try to generate typescript classes.  Fail.  Download source of MetadataGenerator.  Find a few small issues that caused me a lot of headaches.  Get a response from the repo team basically saying "it's free, what do you expect".......

If you open the MetadataGenerator repo to me I'll PR my small changes as you suggested.

<< mike

**Comment by marcelgood** [comment]
I'm gonna close this issue. We really don't need such a negative attitude here. I understand that this is coming out of frustration, and there are probably issues in the tool. I'm not sure why you would still use EF5. Performance is worse than EF6 etc and it's a straight forward upgrade to EF6.

I will take a look at why the tooling is failing in temphire.angular. It's most likely because other libraries have been updated with breaking changes. I didn't have to re-generate the entities for temphire in a while.

We appreciate the community pointing out issues with the code that we publish, but please don't be rude.

**Comment by marcelgood** [comment]
One final update. The tooling seems to work fine in temphire. The final metadata is actually generated by tsgen-core.js and is output in the form of metadata.ts next to the entity classes. The native option in the .exe was actually an experimental option, and I think there is something missing. It forks a node process to do the conversion. 

Here's my run against an empty entities folder. There's one known bug that we haven't fixed yet. The output folder must exsist, otherwise it fails. If you delete the entire entities folder it will fail, because the tool doesn't create the folder.

```
> temphire-angular@1.0.0 metadata-entities C:\Workspace\Frameworks\temphire.angular\TempHire
> npm run metadata && npm run entities


> temphire-angular@1.0.0 metadata C:\Workspace\Frameworks\temphire.angular\TempHire
> .\tools\bin\MetadataGenerator.exe -i ..\DomainModel\bin\Debug\DomainModel.dll -o metadata.json

MetadataGenerator -i ..\DomainModel\bin\Debug\DomainModel.dll -o metadata.json

> temphire-angular@1.0.0 entities C:\Workspace\Frameworks\temphire.angular\TempHire
> node ./tools/tsgen.js

Generating typescript classes...
Input: C:\Workspace\Frameworks\temphire.angular\TempHire\metadata.json
Source: C:\Workspace\Frameworks\temphire.angular\TempHire\app\core\entities
Output: C:\Workspace\Frameworks\temphire.angular\TempHire\app\core\entities
CamelCase: true
Injected base class: EntityBase

C:\Workspace\Frameworks\temphire.angular\TempHire>
```
